site_name: 彼岸的笔记
site_url: https://bi-an.github.com/learning_books
#theme: material
theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - cpp
    - java
  analytics:
    gtag: G-ABC123
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  #nav style can be dark or light
  nav_style: dark

# Navigation
nav:
  - 首页: index.md
  - 书籍:
    - CUDA编程: 
      - CUDA简介: book_notes/CUDA_programming/README.md
    - GNU make手册:
      - book_notes/GNU_make/index.md
      - 第2章 Makefile简介:
        - book_notes/GNU_make/introduction/index.md
      - 第3章 写Makefile:
        - book_notes/GNU_make/writing_makefiles/index.md
      - 杂项:
        - 'book_notes/GNU_make/miscellaneous/index.md'
        - recipes: 'book_notes/GNU_make/miscellaneous/recipes.md'
  - 博客:
    - blog/index.md
    - C++: 'blog/cplusplus/index.md'
    - 英语:
      - 'blog/English/index.md'
      - 常见缩写词: 'blog/English/abbr.md'
    - Shell:
      - blog/shell/index.md

