site_name: 彼岸的读书笔记
site_url: https://bi-an.github.com/learning_books
#theme: readthedocs
theme: material

# Configuration
# If there is no the following configuration, the default configuration will be used.
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # default scheme is light mode, can change to "slate" for dark mode
    - scheme: default
      #primary: orange
      #accent: orange
      #toggle:
        #icon: material/toggle-switch-off-outline
        #name: Switch to dark mode
    - scheme: slate
      #primary: orange
      #accent: orange
      #toggle:
        #icon: material/toggle-switch
        #name: Switch to light mode
  font:
    # Pick up a font from https://fonts.google.com/
    text: Noto Sans Simplified Chinese
    code: Consolas

# Navigation
nav:
  - 首页: index.md
  - 书籍笔记:
    - CUDA编程: 
      - CUDA简介: book_notes/CUDA_programming/README.md
    - GNU make手册:
      - book_notes/GNU_make/index.md
      - 第2章 Makefile简介:
        - book_notes/GNU_make/introduction/index.md
      - 第3章 写Makefile:
        - book_notes/GNU_make/writing_makefiles/index.md
      - 杂项:
        - 'book_notes/GNU_make/miscellaneous/index.md'
        - recipes: 'book_notes/GNU_make/miscellaneous/recipes.md'
  - 个人博客:
    - blog/index.md
    - C++: 'blog/cplusplus/index.md'
    - 英语:
      - 'blog/English/index.md'
      - 常见缩写词: 'blog/English/abbr.md'
    - Shell:
      - blog/shell/index.md

