site_name: 彼岸的笔记
site_url: https://bi-an.github.com/learning_books
theme:
  name: material
  features:
    - navigation.tabs

# Extensions
markdown_extensions:
  # Show contents of a markdown file
  - toc:
      permalink: true
  # Enable "note, tip..." block
  - admonition
  # Enable collapsible function of admonition feature
  - pymdownx.details
  # Block configure
  - pymdownx.highlight
  - pymdownx.inlinehilite
  # Enable content tabs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  # Enable footnote feature
  - footnotes
  # Enable tilde character(~) for delete and subscript
  - pymdownx.tilde
  # Enable caret character(^) for insert and superscript
  - pymdownx.caret
  # Enable LaTeX math equations, which requires extra js below
  - pymdownx.arithmatex:
      generic: true
  # Enable emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Enable attributes for button links
  - attr_list
  # Enable metadata for tags
  - meta
  # Enable markdown in html for home page
  - md_in_html
  - tables

# Navigation
nav:
  - 首页: index.md
  - 书籍:
    - CUDA编程: 
      - CUDA简介: book_notes/CUDA_programming/README.md
    - GNU make手册:
      - book_notes/GNU_make/index.md
      - 第2章 Makefile简介:
        - book_notes/GNU_make/introduction/index.md
      - 第3章 写Makefile:
        - book_notes/GNU_make/writing_makefiles/index.md
      - 杂项:
        - 'book_notes/GNU_make/miscellaneous/index.md'
        - recipes: 'book_notes/GNU_make/miscellaneous/recipes.md'
  - 博客:
    - blog/index.md
    - C++: 'blog/cplusplus/index.md'
    - 英语:
      - 'blog/English/index.md'
      - 常见缩写词: 'blog/English/abbr.md'
    - Shell:
      - blog/shell/index.md

