site_name: 彼岸的读书笔记
site_url: https://bi-an.github.com/learning_books
#theme: readthedocs
theme: material

# Navigation
nav:
  - 首页: index.md
  - 书籍笔记:
    - CUDA编程: 
      - CUDA简介: book_notes/CUDA_programming/README.md
    - GNU make手册:
      - book_notes/GNU_make/index.md
      - 第2章 Makefile简介:
        - book_notes/GNU_make/introduction/index.md
      - 第3章 写Makefile:
        - book_notes/GNU_make/writing_makefiles/index.md
      - 杂项:
        - 'book_notes/GNU_make/miscellaneous/index.md'
        - recipes: 'book_notes/GNU_make/miscellaneous/recipes.md'
  - 个人博客:
    - blog/index.md
    - C++: 'blog/cplusplus/index.md'
    - 英语:
      - 'blog/English/index.md'
      - 常见缩写词: 'blog/English/abbr.md'
    - Shell:
      - blog/shell/index.md

